services:
  trino:
    image: eclipse-temurin:${TRINO_IMAGE_TAG}
    ports:
      - "28080:8080"
      - "29043:9043"
      - "5005:5005"
    container_name: trino
#    user: root
    mem_limit: 2g
    environment:
      - HADOOP_USER_NAME=root
    entrypoint: /bin/bash /tmp/trino/init.sh
    volumes:
      - ./conf/trino:/etc/trino
      - ./init/trino:/tmp/trino
      - ./init/common:/tmp/common
      - ./healthcheck:/tmp/healthcheck
      - ~/project/trino/core/trino-server/target/trino-server-480.tar.gz:/usr/lib/trino-server.tar.gz
      - ./sql/trino:/tmp/sql
    depends_on:
      - kafka
#    healthcheck:
#      test: ["CMD", "/tmp/healthcheck/trino-healthcheck.sh"]
#      interval: 120s
#      timeout: 60s
#      retries: 5
#      start_period: 60s

  jeager:
    image: jaegertracing/all-in-one:${JAEGER_IMAGE_TAG}
    ports:
      - "16686:16686"
      - "4317:4317"
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:${PROMETHEUS_IMAGE_TAG}
    container_name: prometheus
    ports:
      - "29090:9090"
    volumes:
      - ./init/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:${GRAFANA_IMAGE_TAG}
    container_name: grafana
    ports:
      - "23000:3000"
    volumes:
      - ./init/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./init/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./init/grafana/dashboards:/etc/grafana/provisioning/dashboards

  kafka:
    image: apache/kafka:${KAFKA_IMAGE_TAG}
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      # it's important for single node in Kafka cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
