services:
  trino:
    image: eclipse-temurin:${TRINO_IMAGE_TAG}
    ports:
      - "28080:8080"
      - "29043:9043"
      - "5005:5005"
    container_name: trino
#    user: root
    mem_limit: 2g
    environment:
      - HADOOP_USER_NAME=root
    entrypoint: /bin/bash /tmp/trino/init.sh
    volumes:
      - ./conf/trino:/etc/trino
      - ./init/trino:/tmp/trino
      - ./init/common:/tmp/common
      - ./healthcheck:/tmp/healthcheck
      - ~/project/trino/core/trino-server/target/trino-server-480.tar.gz:/usr/lib/trino-server.tar.gz
      - ./sql/trino:/tmp/sql
    healthcheck:
      test: ["CMD", "/tmp/healthcheck/trino-healthcheck.sh"]
      interval: 120s
      timeout: 60s
      retries: 5
      start_period: 60s

  jeager:
    image: jaegertracing/all-in-one:${JAEGER_IMAGE_TAG}
    ports:
      - "16686:16686"
      - "4317:4317"
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true