services:
  trino:
    image: eclipse-temurin:${TRINO_IMAGE_TAG}
    ports:
      - "28080:8080"
      - "29043:9043"
      - "5005:5005"
    container_name: trino
#    user: root
    mem_limit: 2g
    environment:
      - HADOOP_USER_NAME=root
    entrypoint: /bin/bash /tmp/trino/init.sh
    volumes:
      - ./conf/trino:/etc/trino
      - ./init/trino:/tmp/trino
      - ./init/common:/tmp/common
      - ./healthcheck:/tmp/healthcheck
      - ~/project/trino/core/trino-server/target/trino-server-480.tar.gz:/usr/lib/trino-server.tar.gz
      - ./sql/trino:/tmp/sql
    depends_on:
      - kafka
      - hive-metastore
#    healthcheck:
#      test: ["CMD", "/tmp/healthcheck/trino-healthcheck.sh"]
#      interval: 120s
#      timeout: 60s
#      retries: 5
#      start_period: 60s

  jeager:
    image: jaegertracing/all-in-one:${JAEGER_IMAGE_TAG}
    ports:
      - "16686:16686"
      - "4317:4317"
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:${PROMETHEUS_IMAGE_TAG}
    container_name: prometheus
    ports:
      - "29090:9090"
    volumes:
      - ./init/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:${GRAFANA_IMAGE_TAG}
    container_name: grafana
    ports:
      - "23000:3000"
    volumes:
      - ./init/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./init/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./init/grafana/dashboards:/etc/grafana/provisioning/dashboards

  kafka:
    image: apache/kafka:${KAFKA_IMAGE_TAG}
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      # it's important for single node in Kafka cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1

  minio:
    image: minio/minio:${MINIO_IMAGE_TAG}
    container_name: minio
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DOMAIN: minio
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

  hive-metastore:
    # https://github.com/starburstdata/hive3
    image: starburstdata/hive:${HIVE_IMAGE_TAG}
    container_name: hive-metastore
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"

      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./init/postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 120s
      retries: 5
      start_period: 2s