coordinator = true
node-scheduler.include-coordinator = true
http-server.http.port = 8080
discovery.uri = http://0.0.0.0:8080
catalog.management=dynamic

tracing.enabled=true
otel.exporter.endpoint=http://jaeger:4317

event-listener.config-files=etc/kafka-event-listener.properties