event-listener.name=kafka
kafka-event-listener.broker-endpoints=kafka:9092

kafka-event-listener.publish-created-event=false
#kafka-event-listener.created-event.topic=query_create

kafka-event-listener.completed-event.topic=trino_query_complete
kafka-event-listener.client-id=trino-example